#+TITLE: org-books
#+AUTHOR: Abhinav Tushar
#+AUTHOR: Andre Goderich

Reading list management using org-mode.
Original author: @lepisma (Abhinav Tushar): https://github.com/lepisma/org-books.

This is my fork with some additional functionality I wanted for myself.
All credit for the package goes to @lepisma.
See the original version for a tutorial.

* Differences from the original version

- More details from Goodreads.
- Automated property and state assignment with in-built functions.
- Re-read tracking.
- Jump to reading: quickly find books that you are reading right now.
- New reading state: DNF! For books you cannot even. (Supports re-read functionality!)
- Quality of life improvements:
  + If org-books-add-url fails, it will ask to retry.
  + Helm call for location of new book has been simplified, and should run faster.

** Goodreads details

The function =org-books-get-details-goodreads= now fetches
not just the author and book name,
but also the publication year, page count, and Goodreads rating.
Some books have the publication year for a newer edition,
and the original publication year in parentheses:
in these cases the function fetches the original publication year.
The function also adds a timestamp
of the date the book was added to the collection.

** State tracking and re-reads

I rehauled the =org-books-rate-book= function and added a counterpart
for beginning a book: =org-books-start-reading=.
These function now do two things:

- set the TODO state ('READING' or 'READ'),
- add a timestamp to the book's properties.

Moreover, the functions support re-reads.
On every new read, the new starting date,
completion date, and rating are all recorded separately.

* Core functions for everyday use

Consider giving keybindings to the following functions:

- =org-books-add-url=: to add new books to the collection.
  + Alternatively =org-books-cliplink= to add a link from the clipboard.
- =org-books-start-reading=: when beginning to read a new book
  (to change its state to READING and timestamp the starting date).
- =org-books-rate-book=: when you finish a book
  (to give it a rating from 1 to 5, change its state to READ,
  and timestamp the finished date).
  + =org-books-dnf=: if for whatever reason you cannot keep reading,
    abandon ship and mark the book as unfinished.
- =org-books-jump-to-reading=: quickly find a book with a READING status.
  You can use this anywhere, not just in the org-books file.
